steps:
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - 'gs://software.redpillanalytics.io/database/oracle-database-xe-18c-1.0-1.x86_64.rpm'
    - '12.2.1.4.0'
  id: copy-database
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - 'gs://software.redpillanalytics.io/fmw/fmw_12.2.1.3.0_infrastructure.jar'
    - '12.2.1.4.0'
  id: copy-fmw
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - 'gs://software.redpillanalytics.io/obi/bi_platform-12.2.1.4.0_linux64.bin'
    - '12.2.1.4.0'
  id: copy-obi-1
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - 'gs://software.redpillanalytics.io/obi/bi_platform-12.2.1.4.0_linux64-2.zip'
    - '12.2.1.4.0'
  id: copy-obi-1
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/obi
  - --cache=true
  - --cache-ttl=48h
  - --dockerfile=12.2.1.4.0/Dockerfile
  - --context=/workspace/12.2.1.4.0
  id: kaniko-build
timeout: 7200s
