name: Build and Publish Docker Image
on:
  push:
    branches:
    - master
    paths:
    - '*'
    - '12.2.1.4.0/*'
  pull_request:
    paths:
    - '*'
    - '12.2.1.4.0/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download Installation Media for JDK
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp s3://software.redpillanalytics.io/oracle/java/jdk-8u221-linux-x64.rpm ./12.2.1.4.0/.
    - name: Download Installation Media for OBI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp s3://software.redpillanalytics.io/oracle/obi/12.2.1.4.0/* ./12.2.1.4.0/.
    - name: Build and Publish Image
      run: ./docker-publish -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} -d 12.2.1.4.0
