name: Build and Publish Docker Image
on:
  push:
    branches:
    - master
    paths:
    - '*'
    - '12.2.1.4.0/*'
  pull_request:
    paths:
    - '*'
    - '12.2.1.4.0/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish Image
      run: ./docker-publish -i redpillanalytics/obi -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} -d 12.2.1.4.0
